### ISSUE TITLE
unsharing and resharing (via CLI)

### ISSUE THREAD

**Issue by kokos76** [micahmo/WireGuardServerForWindows#1]
Hi! Thanks for your hard work! 

> A reboot may still cause the the internet sharing to fail, even though the Internet Connection Sharing service is running, and the network interface indicates that it is sharing in Control Panel. Only unsharing and resharing can fix this.

1) How to do it (unsharing and resharing)? Just click the "Disable internet sharing" button?
2)Maybe you can check the server's health after restarting Windows and restore it if necessary?

**Comment by micahmo** [comment]
Hi @kokos76, thanks for checking out the project!

Yes, after rebooting, run the app, choose "Disable Internet Sharing" and then "Enable Internet Sharing".

And yes, there are definitely ways to do this automatically. Unfortunately, a standalone (run-time) app can't do much without user intervention. I had an idea to register a Windows service when the user selects "Enable Internet Sharing" that would be set to start automatically. It could then do the necessary checks and fixups on startup. Not sure if I'll get around to that unless demand/usage of this project goes up. :-) I'm also open to contributions!

**Comment by kokos76** [comment]
Please just make a CLI interface first, for example --restartinternetsharing. In this case, right now it will be possible to create a task in the Windows Scheduler to run the WireGuardServerForWindows.exe --restartinternetsharing command.

**Comment by micahmo** [comment]
Hi @kokos76, I just pushed a new version ([v1.5](https://github.com/micahmo/WireGuardServerForWindows/releases/tag/v1.5)) that includes a new CLI (`ws4w.exe`) with a `restartinternetsharing` option as you suggested. There is also a [new section in the README](https://github.com/micahmo/WireGuardServerForWindows/#internet-sharing-workaround) that describes how to set it up in Task Scheduler to fix the internet sharing after reboot. Seems to work nicely on my system. :-) Free free to grab the latest (in-app auto update should detect it) and give it a spin.

Thanks again for the suggestion!

**Comment by kokos76** [comment]
Thanks a lot!
