### ISSUE TITLE
I cannot ping after a successful handshake.

### ISSUE THREAD

**Issue by cweijan** [micahmo/WireGuardServerForWindows#12]
I have successfully shaken hands, but I can't ping.
![image](https://user-images.githubusercontent.com/27798227/140272187-2b9006d6-ec44-4f10-8d79-0a27b3b374af.png)
![image](https://user-images.githubusercontent.com/27798227/140272307-93a588d6-88da-4f8b-be13-1938a5957a0f.png)
The following is the configuration of my client, the allow ip is inconsistent with the server, Is this caused by the allow ip of the client?
![image](https://user-images.githubusercontent.com/27798227/140272372-0bcccee0-79ef-40f2-90c9-a60534dd6dd3.png)
![image](https://user-images.githubusercontent.com/27798227/140272784-5cd93d2f-e135-432b-b88f-69ceddea82f9.png)

**Comment by micahmo** [comment]
Hi @cweijan. Your configuration looks fine. The meaning of AllowedIPs is a bit confusing in WireGuard terminology.

> ![](https://user-images.githubusercontent.com/27798227/140272372-0bcccee0-79ef-40f2-90c9-a60534dd6dd3.png)

In this context (from the server), AllowedIPs defines the set of IPs that the client is allowed to connect with. In this case, your client can only connect as `10.253.0.3`, which is fine.

> ![](https://user-images.githubusercontent.com/27798227/140272784-5cd93d2f-e135-432b-b88f-69ceddea82f9.png)

In this context (from the client), you'll notice that AllowedIPs is under the `[Peer]` heading, meaning that it refers to the server. Here it is saying that any requests to `10.253.0.0/24` will be routed to the server.

The more important value in this screenshot is the Address under your `[Interface]` (the client). You'll notice it's `10.253.0.3/32`, which matches what the server expects you to connect from. The fact that you get a successful handshake means the server did accept your request.

Now you're trying to ping from the server to the client, correct? There could be any number of reasons why that doesn't work. Ensure that your client machine is not blocking ping via firewall. Perhaps try other ways of connecting, like SMB (`\\10.253.0.3`).

You can also try some tests from the client side. Can the client ping the server or access the server filesystem over SMB? Can the client access the internet? If so, can you see if the client's internet access is being routed through the server's ISP ([whoismyisp.org](https://www.whoismyisp.org/))?

**Comment by cweijan** [comment]
You answered my doubts about allow_ip, it is very helpful, my configuration is correct, then it may be related to the ISP, thank you for your reply.

**Comment by cweijan** [comment]
I refer to the [article](https://www.henrychang.ca/how-to-setup-wireguard-vpn-server-on-windows/) in the readme, and found that your software has one step less work. After I modified the registry according to the article, the network can work normally.
![image](https://user-images.githubusercontent.com/27798227/140384040-328562f9-58b8-4ec6-a5a0-c4a79452d0ce.png)
I change to below.
![image](https://user-images.githubusercontent.com/27798227/140384105-2f22307f-ae1d-4398-ae7f-3302fe5232c7.png)
Now it work!
![image](https://user-images.githubusercontent.com/27798227/140384157-e6b1c4e9-37ff-41b8-b6c1-3743f5546a23.png)

**Comment by micahmo** [comment]
Awesome, nice job finding that!

However, the program is supposed to make that change. You can even see that registry key is referenced in the code [here](https://github.com/micahmo/WireGuardServerForWindows/blob/dfff7b3e1026ac01c6f39c27ae4016d931c56ec1/WireGuardServerForWindows/Models/ServerConfigurationPrerequisite.cs#L233). This is supposed to happen whenever you change the `Address` property in the Server Configuration.

Would be willing to try changing that to something else (you can change it back after) to see if the registry key remains unchanged? If so, there maybe a problem with the application accessing that key. (Are you running the app as Admin?)

**Comment by cweijan** [comment]
I tried to modify the address, but the registry does not seem to be updated (I have refreshed)
![image](https://user-images.githubusercontent.com/27798227/140499880-5ac380c7-bb81-4cc6-a69a-a6f094f1f954.png)

**Comment by micahmo** [comment]
@cweijan Thanks, I appreciate you trying that! However, I would not expect the change you made to affect the registry. That's because the `Address` field in the Server Configuration page is defining the valid addresses for your whole WireGuard network in CIDR notation. When it says `/24` at the end, it means the first 24 bits are reserved for the network (`10.253.0`) and the last 6 bits can change for each address that is assigned to each device on the network. The server itself gets the first valid address in the specified range, `10.253.0.1`, and each of your clients gets a subsequent address, `10.253.0.2`, etc.

Therefore, in order for the registry entry to change, you would have to change one of the reserved bits so that the whole address range is changed.

Would you be willing to try `10.254.0.0/24`?

Again, I appreciate your help with this!

**Comment by cweijan** [comment]
Yes, it did change.
![image](https://user-images.githubusercontent.com/27798227/140508970-34d76d87-4928-48b2-8c69-7426d085c529.png)

**Comment by cweijan** [comment]
I think this is caused by not modifying the registry when setting it for the first time.
I clear AppData\Roaming\WS4W data, then reinitialize, registry not get changed.
![image](https://user-images.githubusercontent.com/27798227/140510194-be9c8bed-fd4e-4459-b616-83d0c4a30fa9.png)
I already know the cause of the problem, that's enough.

**Comment by micahmo** [comment]
@cweijan Great, thanks again for the help! I will investigate the issue of not populating the registry value upon first configuration.

P.S. Some of your screenshots have private keys that you may want to hide. :-)
