### ISSUE TITLE
enable the internet sharing function ,but encounter error message 

### ISSUE THREAD

**Issue by yea73920** [micahmo/WireGuardServerForWindows#16]
Dear Micahmo,

I ever set the server and client connected successfully,but when I restart WS4W ,the internet sharing symbol would be "X" ,
I try to enable and reconnect the internet, but it will show an error message as the images display,

https://imgur.com/a/dnJBjXN
https://imgur.com/5MboKPa

Could you help me fix it? 

thank you very much

**Comment by micahmo** [comment]
Hi @yea73920, thanks for raising this issue! I had actually seen the exact same thing on my system, but hadn't had time to investigate yet. :-) Enabling a virtual switch for Hyper-V seemed to trigger the issue for me, and I see that you also have a virtual switch.

I have good news and bad news.

I did find that someone has seen this exact error (trying to accomplish the same thing) in another project: utapyngo/icsmanager#17

Using their discussion, I have incorporated a similar fix into WS4W and published a new version [here](https://github.com/micahmo/WireGuardServerForWindows/releases/tag/v1.6.1). Unfortunately, that fix didn't work on my system, so I had to contrive a manual workaround.

The good news is that the manual workaround solves the issue. I have documented it in the README here: https://github.com/micahmo/WireGuardServerForWindows#inability-to-enable-internet-sharing


Please update to the latest version, try the workaround (if necessary), and let me know how it goes.

**Comment by yea73920** [comment]
Hi @micahmo ,

 thanks for your reply, I installed the new version and try the workaround ,it's work

thank you so much :)

**Comment by yllekz** [comment]
I'm experiencing this issue in the new version. What is the fix?

**Comment by micahmo** [comment]
Glad to hear it's working for you now!
