### ISSUE TITLE
connected but no internet

### ISSUE THREAD

**Issue by dajoka** [micahmo/WireGuardServerForWindows#21]
Hi, from my iPhone I connected successfully with cell data to home windows wireguard:.
Here's server status:

interface: wg_server
  public key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
  private key: (hidden)
  listening port: 51820

peer: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
  preshared key: (hidden)
  endpoint: 174.xx.xx.xx:13670
  allowed ips: 10.253.0.2/32
  latest handshake: 13 seconds ago
  transfer: 38.24 KiB received, 6.50 KiB sent

But I cannot access internet or my home LAN from iPhone when connected to wireguard..

Any ideas?

Thank you!

**Comment by dajoka** [comment]
ok, i feel stupid. Bad dns typo in client config.

So now, I can browse the web "through" my home connection, BUT, I'd love to be able to access LAN also. I have a music server and other stuff I'd love to access. Currently I can't. Any ideas on how to be able to?

**Comment by dajoka** [comment]
well, this section should be called "user ignorance issues", not "issues."

There are NO issues. It's all working now.

Some local dns issues.

All working and thank you for a great product, @micahmo

**Comment by micahmo** [comment]
Hey @dajoka, glad to hear you sorted everything out! Just curious about your setup, it sounds like you are using a local DNS server for the WireGuard clients with the goal of accessing LAN resources by name, correct?
