### ISSUE TITLE
Suggestion: Optional NAT routing task

### ISSUE THREAD

**Issue by rwayboy** [micahmo/WireGuardServerForWindows#28]
Hello again. So I observed that when you enable NAT routing, a task is created in task scheduler that executes the setnetipaddress using your app on system startup.

Since I am using a WiFi network, it takes a while until my WiFi adapter automatically connects to my WiFi network on system startup, so when the task is executed, there isn't a wireguard tunnel to receive the IP address and subnet mask. As a result, the clients do not have internet access.

This is an issue I had been having even when I was manually setting up wireguard in the past, so this isn't an issue with your app. Of course, an ethernet connection would solve this, but it is not possible for me at the moment.

As a workaround for this, I have created a custom task in task scheduler that runs a .bat file that waits a few seconds before setting the IP address in the wireguard tunnel at system startup.

I tried to delete the task that the application creates, but it seems to come back after every restart. Would it be possible to add a checkbox at the "NAT Routing" section, that would let us decide if we want the task?

Thank you for your time.

**Comment by okastl** [comment]
I second this. Please make the "setnetipaddress" call from task scheduler optional. In case someone wants to have an own script run at startup, which might interfere with the default task. Thank you.

**Comment by micahmo** [comment]
Hey all, the latest release ([v1.7.3](https://github.com/micahmo/WireGuardServerForWindows/releases/tag/v1.7.3)) should address this issue. There is now an option to disable the Windows Task related to NAT routing.

I also added a slight delay when the task is enabled, so it might help to solve the original issue (when the main interface is connecting to WiFi), but if not, it can now be disabled.

**Comment by micahmo** [comment]
FYI, version [2.0.9](https://github.com/micahmo/WgServerforWindows/releases/tag/v2.0.9) adds the ability to define a custom delay for the Windows boot tasks.
