### ISSUE TITLE
Suggestion: Ability to change the default folder path of the configurations

### ISSUE THREAD

**Issue by rwayboy** [micahmo/WireGuardServerForWindows#29]
Hello again! Would it be possible to have this as an option?

If this would complicate things, then it would just be convenient if there was a button somewhere in the app that would open the WS4W folder in AppData in order to access the config files quickly.

Thank you for taking the time to read my suggestions.

**Comment by micahmo** [comment]
Hi,

The latest release, [v1.7.4](https://github.com/micahmo/WireGuardServerForWindows/releases/tag/v1.7.4), adds the ability to quickly open the server or client configuration folder. It also adds the ability to change either folder, which migrates any existing configurations to the newly selected folder.
