### ISSUE TITLE
Endpoint ipv6

### ISSUE THREAD

**Issue by lomonosov77** [micahmo/WireGuardServerForWindows#3]
Error when specifying ipv6 of server configuration in the endpoint line

**Comment by micahmo** [comment]
Hi @lomonosov77, good catch! I didn't test any of the IP-related fields for IPv6, so there are likely other problems along this line.

I pushed an update ([1.5.1](https://github.com/micahmo/WireGuardServerForWindows/releases/tag/v1.5.1)) that allows IPv6 addresses to pass validation in the Endpoint property. They should be formatted with brackets around the address and before the port, as specified by [RFC2732](https://datatracker.ietf.org/doc/html/rfc2732).

Example: `[2001:0db8:85a3:0000:0000:8a2e:0370:7334]:51821`

Note that I don't have a public IPv6 address to test this, so while addresses in the format above are now allowed by WS4W and stored in the WireGuard server config file, I can't prove that WireGuard handles them correctly. If you could grab the latest version  (should be available in-app via auto-update) and try it out, that would be great!

**Comment by micahmo** [comment]
@lomonosov77 Were you able to try the latest release with IPv6?

**Comment by lomonosov77** [comment]
Yes, now there is no error when specifying the ipv6 address!
Thanks!
