### ISSUE TITLE
wg Network may become public after reboot

### ISSUE THREAD

**Issue by okastl** [micahmo/WireGuardServerForWindows#33]
The wg Networks may become public after reboot.
The task scheduler entry re-enables NAT Routing, but Private Network (sometimes?) needs to be re-enabled manually in the WS4W UI.
A simple solution would be to extend the WS4W CLI command to change the network to private, so the task scheduler call on reboot can do both: enable NAT routing and change network to private.

**Comment by okastl** [comment]
As a workaround, I have added another task to task scheduler, which executes a PowerShell script with the following content:

`Set-NetConnectionProfile -InterfaceAlias wg_server -NetworkCategory Private
`

This works, but isn't ... elegant.

**Comment by micahmo** [comment]
Thanks for sharing, @okastl! When I'm able to fix this in the application, I will probably do something very similar, so I wouldn't say it's not elegant. 😊

**Comment by micahmo** [comment]
Hey @okastl, this feature has been added in the latest release, [1.7.6](https://github.com/micahmo/WireGuardServerForWindows/releases/tag/v1.7.6).
